# 基础配置
SYSTEM_NAME = "FlyBoat"
ZMS_MAGIC = "0x1348ad6"
PROCESS_NAME = "python"
ROOT_PATH_NAME = "FlyBoat"

# MinIO 配置
MINIO_ACCESS_KEY = ""
MINIO_SECRET_KEY = ""
CSV_BUCKET = ""
EXCEL_BUCKET = ""
JSON_BUCKET = ""
MODEL_BUCKET = ""
IMAGE_BUCKET = ""
NOTEBOOK_BUCKET = ""
MINIO_URL = ""
MINIO_SCHEME_AND_URL = f"http://{MINIO_URL}"

# 阿里云 OSS 配置
ALI_CNAME = ""
ALI_ACCESS_KEY = ""
ALI_SECRET_KEY = ""
ALI_CSV_BUCKET = ""
ALI_EXCEL_BUCKET = ""
ALI_JSON_BUCKET = ""
ALI_MODEL_BUCKET = ""
ALI_IMAGE_BUCKET = ""
ALI_NOTEBOOK_BUCKET = ""
ALI_OSS_ENDPOINT = ""
ALI_OSS_REGION = ""
ALI_OSS_SCHEME_AND_URL = f"https://{ALI_OSS_ENDPOINT}"


# Notebook 本地存储路径
NOTEBOOK_LOCAL_FOLDER = ""


# 钉钉监控配置
ROBOT_URL = ""
ROBOT_ACCESS_TOKEN = ""

# 发布 BaseURL
PUBLISH_HOST = ""

# 达梦配置
DM_HOST = ""
DM_PORT = 5236
DM_USER = ""
DM_PASSWORD = ""

DM_HOST2 = ""
DM_PORT2 = 5236
DM_USER2 = ""
DM_PASSWORD2 = ""

# 达梦测试环境配置
DM_HOST_TEST = ""
DM_PORT_TEST = 5236
DM_USER_TEST = ""
DM_PASSWORD_TEST = ""

# Oracle 配置
ORACLE_HOST = ""
ORACLE_PORT = 1524
ORACLE_USER = ""
ORACLE_PASSWORD = ""
ORACLE_SERVICE_NAME = "orcl"

ORACLE_HOST2 = ""
ORACLE_PORT2 = 1524
ORACLE_USER2 = ""
ORACLE_PASSWORD2 = ""
ORACLE_SERVICE_NAME2 = "orcl"

# WebSocket 地址配置
WEBSOCKET_URL = ""

DataBase = "oracle"
Oss = "s3"
